version: 2.0
workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: stable
    triggers:
      push:
        branches:
          only:
            - main
    scripts:
      pre-commit:
        - flutter pub get
      - name: Build iOS app
        script: |
          flutter build ios
      - name: Test iOS app
        script: |
          flutter test
